# Generated by Django 5.2.6 on 2025-09-20 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('contract_identifier', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('photo_location', models.CharField(choices=[('FRONT_VIEW', 'Front View'), ('REAR_VIEW', 'Rear View'), ('LEFT_SIDE', 'Left Side'), ('RIGHT_SIDE', 'Right Side'), ('HOOKUP', 'Hookup'), ('DAMAGE', 'Damage'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.equipment')),
            ],
        ),
    ]
