# Generated by Django 5.2.6 on 2025-10-01 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionphoto',
            name='photo_type',
            field=models.CharField(choices=[('BEFORE', 'Before (Check-Out)'), ('AFTER', 'After (Check-In)')], default='AFTER', max_length=10),
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(choices=[('SCRATCH', 'Scratch/Scuff'), ('DENT', 'Dent'), ('BROKEN', 'Broken Part'), ('MISSING', 'Missing Part'), ('OTHER', 'Other')], max_length=50)),
                ('notes', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='api.conditionphoto')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
