# Generated by Django 5.2.6 on 2025-10-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conditionphoto_photo_type_damagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='requires_hookup',
            field=models.BooleanField(default=False),
        ),
    ]
