# Generated by Django 5.2.6 on 2025-10-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_equipment_requires_hookup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='requires_hookup',
        ),
    ]
