# Generated by Django 5.2.6 on 2025-10-08 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_equipment_requires_hookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='api.equipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='damage_photos/'),
        ),
    ]
