# Generated by Django 5.2.6 on 2025-10-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_damagereport_equipment_alter_damagereport_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='damage_location',
            field=models.CharField(choices=[('FRONT', 'Front'), ('REAR', 'Rear'), ('LEFT', 'Left Side'), ('RIGHT', 'Right Side'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
