# Generated by Django 5.2.6 on 2025-10-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_conditionphoto_uploaded_by_alter_damagereport_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="damagereport",
            options={"ordering": ["-reported_at"]},
        ),
        migrations.RenameField(
            model_name="conditionphoto",
            old_name="image",
            new_name="photo",
        ),
        migrations.AlterField(
            model_name="conditionphoto",
            name="photo_location",
            field=models.CharField(
                choices=[
                    ("FRONT_VIEW", "Front View"),
                    ("REAR_VIEW", "Rear View"),
                    ("REAR_VIEW", "Rear View"),
                    ("LEFT_SIDE", "Left Side"),
                    ("RIGHT_SIDE", "Right Side"),
                    ("HOOKUP", "Hookup"),
                    ("DAMAGE", "Damage"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
